version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-node-tut
    restart: always
    ports:
      - 4026:8080
    command: Xvfb :99 -screen 0 1024x768x16 npm start
    environment:
      DISPLAY: 10.0.75.1:0.0
    env_file: .env